import type { Room } from './types';

export const mockRooms: Room[] = [
  {
    id: '1',
    slug: 'deluxe-suite',
    name: 'Deluxe Suite',
    shortDescription: 'Spacious suite with panoramic views',
    description:
      'Experience the ultimate in luxury with our Deluxe Suite, featuring floor-to-ceiling windows overlooking the resort grounds, marble bathroom with soaking tub, and premium bedding.',
    images: [
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80',
      'https://images.unsplash.com/photo-1582719471384-894fbb16e074?w=800&q=80',
      'https://images.unsplash.com/photo-1578926078328-123ec05461b6?w=800&q=80',
    ],
    amenities: [
      'King Bed',
      'Mini Bar',
      'Work Desk',
      'WiFi',
      'Marble Bathroom',
      'Bath Robes',
      'Premium Toiletries',
      'Flat Screen TV',
    ],
    bedType: 'king',
    capacity: 2,
    nightlyRate: 350,
    nightlyRateOriginal: 400,
    availability: {
      available: 8,
      occupied: 5,
    },
    features: ['Ocean View', 'Balcony', 'Lounge Area'],
    viewType: 'Ocean',
    squareFeet: 550,
    checkInTime: '3:00 PM',
    checkOutTime: '11:00 AM',
  },
  {
    id: '2',
    slug: 'presidential-villa',
    name: 'Presidential Villa',
    shortDescription: 'Ultra-luxury villa with private pool',
    description:
      'Our most exclusive accommodation features a private infinity pool, separate living areas, butler service, and breathtaking resort views. The perfect choice for discerning guests.',
    images: [
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80',
      'https://images.unsplash.com/photo-1582719471384-894fbb16e074?w=800&q=80',
      'https://images.unsplash.com/photo-1578926078328-123ec05461b6?w=800&q=80',
    ],
    amenities: [
      'Two King Beds',
      'Private Pool',
      'Butler Service',
      'Wine Cellar',
      'Home Theater',
      'Spa Bath',
      'Sauna',
      'Chef Kitchen',
    ],
    bedType: 'king',
    capacity: 4,
    nightlyRate: 950,
    availability: {
      available: 2,
      occupied: 1,
    },
    features: ['Private Pool', 'Garden', 'Terrace', 'Mountain View'],
    viewType: 'Mountain',
    squareFeet: 1200,
    checkInTime: '2:00 PM',
    checkOutTime: '12:00 PM',
  },
  {
    id: '3',
    slug: 'garden-room',
    name: 'Garden Room',
    shortDescription: 'Charming room with garden access',
    description:
      'Enjoy the beauty of nature from your private terrace overlooking lush gardens. Our Garden Rooms offer comfort and tranquility with easy access to the resort grounds.',
    images: [
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80',
      'https://images.unsplash.com/photo-1582719471384-894fbb16e074?w=800&q=80',
      'https://images.unsplash.com/photo-1578926078328-123ec05461b6?w=800&q=80',
    ],
    amenities: [
      'Double Bed',
      'Garden Terrace',
      'WiFi',
      'Ensuite Bathroom',
      'Fresh Linens',
      'Work Desk',
      'TV',
    ],
    bedType: 'double',
    capacity: 2,
    nightlyRate: 200,
    availability: {
      available: 15,
      occupied: 10,
    },
    features: ['Garden View', 'Terrace', 'Direct Garden Access'],
    viewType: 'Garden',
    squareFeet: 350,
    checkInTime: '3:00 PM',
    checkOutTime: '11:00 AM',
  },
  {
    id: '4',
    slug: 'twin-room',
    name: 'Twin Room',
    shortDescription: 'Perfect for business or friends',
    description:
      'Our Twin Room features two comfortable beds and is ideal for business travelers or friends traveling together. Equipped with modern amenities and convenient workspace.',
    images: [
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80',
      'https://images.unsplash.com/photo-1582719471384-894fbb16e074?w=800&q=80',
      'https://images.unsplash.com/photo-1578926078328-123ec05461b6?w=800&q=80',
    ],
    amenities: [
      'Twin Beds',
      'Work Desk',
      'WiFi',
      'Ensuite Bathroom',
      'TV',
      'Mini Fridge',
      'Air Conditioning',
    ],
    bedType: 'twin',
    capacity: 2,
    nightlyRate: 150,
    nightlyRateOriginal: 180,
    availability: {
      available: 20,
      occupied: 8,
    },
    features: ['City View', 'Quiet Location'],
    viewType: 'City',
    squareFeet: 300,
    checkInTime: '3:00 PM',
    checkOutTime: '11:00 AM',
  },
  {
    id: '5',
    slug: 'queen-comfort',
    name: 'Queen Comfort',
    shortDescription: 'Cozy room with queen bed',
    description:
      'Perfect for couples seeking comfort and value. Our Queen Comfort rooms feature a spacious queen bed, modern amenities, and convenient access to all resort facilities.',
    images: [
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80',
      'https://images.unsplash.com/photo-1582719471384-894fbb16e074?w=800&q=80',
      'https://images.unsplash.com/photo-1578926078328-123ec05461b6?w=800&q=80',
    ],
    amenities: [
      'Queen Bed',
      'WiFi',
      'Ensuite Bathroom',
      'TV',
      'Mini Fridge',
      'Desk',
      'Air Conditioning',
    ],
    bedType: 'queen',
    capacity: 2,
    nightlyRate: 180,
    availability: {
      available: 12,
      occupied: 6,
    },
    features: ['Courtyard View', 'Balcony'],
    viewType: 'Courtyard',
    squareFeet: 320,
    checkInTime: '3:00 PM',
    checkOutTime: '11:00 AM',
  },
  {
    id: '6',
    slug: 'family-villa',
    name: 'Family Villa',
    shortDescription: 'Spacious accommodation for families',
    description:
      'Our Family Villa is designed for guests traveling with children or in groups. Two separate bedrooms, large living area, and family-friendly amenities make it perfect for memorable vacations.',
    images: [
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80',
      'https://images.unsplash.com/photo-1582719471384-894fbb16e074?w=800&q=80',
      'https://images.unsplash.com/photo-1578926078328-123ec05461b6?w=800&q=80',
    ],
    amenities: [
      'Two Bedrooms',
      'Living Room',
      'Kitchen',
      'WiFi',
      'Two Bathrooms',
      'TV',
      'Kids Welcome',
      'Board Games',
    ],
    bedType: 'queen',
    capacity: 4,
    nightlyRate: 450,
    nightlyRateOriginal: 550,
    availability: {
      available: 5,
      occupied: 3,
    },
    features: ['Pool View', 'Terrace', 'Fully Equipped'],
    viewType: 'Pool',
    squareFeet: 750,
    checkInTime: '3:00 PM',
    checkOutTime: '11:00 AM',
  },
];
